# render.yaml
services:
  - type: web
    name: rag-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
